language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_da9c28737796_key -iv $encrypted_da9c28737796_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d